### ISSUE TITLE
"--disk-cache-dir=" switch doesn't work

### ISSUE THREAD

**Issue by A-7666** [czyt/vivaldi_plus#34]
"--disk-cache-dir=" switch is totally ignored.
It is thus impossible to move the cache to a custom location (like for example RAM-disk).
Which is a big pity.

No matter which address is set in "--disk-cache-dir=", the cache is always stored in "Cache" folder one level up from vivaldi.exe/version.dll.

Checked with DLL version 1.5.7.

Could you fix this?

**Comment by czyt** [comment]
yes,the `--disk-cache-dir` is overwritened by the dll,you can use the latest version release which allow you to custom the param,and follow the readme ,create a ini file in the same dir of dll.a sample content should be
```
[dir_setting]
data=%app%\..\Data
cache=%app%\..\Cache
[features]
right_click_close_tab=1
```
you can change by your own
