### ISSUE TITLE
PWA应用右键菜单BUG

### ISSUE THREAD

**Issue by Java2Boy** [czyt/vivaldi_plus#5]
### Environment

版本 113.0.5672.93（正式版本） （64 位）
[Vivaldi++](https://github.com/czyt/vivaldi_plus) 1.5.5 inside

### Steps to Reproduce

1. Telegram Web PWA应用，右键消息无法屏蔽自带菜单，出现浏览器菜单与TG菜单两个重叠
2. Edge 却正常

**Comment by czyt** [comment]
不能复现，我先关闭了
